// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.15.2
// source: command.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RedisBenchmarkSpec 定义 Redis 基准测试的参数
type RedisBenchmarkSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`                                 // 操作类型
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`                             // Redis 服务器地址
	Port          string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`                                     // Redis 服务器端口
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`                             // Redis 密码（可选）
	Requests      string                 `protobuf:"bytes,5,opt,name=requests,proto3" json:"requests,omitempty"`                             // 请求总数
	Clients       string                 `protobuf:"bytes,6,opt,name=clients,proto3" json:"clients,omitempty"`                               // 并发客户端数
	Size          string                 `protobuf:"bytes,7,opt,name=size,proto3" json:"size,omitempty"`                                     // 请求大小（可选）
	Loop          string                 `protobuf:"bytes,8,opt,name=loop,proto3" json:"loop,omitempty"`                                     // 循环次数（可选）
	LoopDuration  string                 `protobuf:"bytes,9,opt,name=loop_duration,json=loopDuration,proto3" json:"loop_duration,omitempty"` // 循环持续时间（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisBenchmarkSpec) Reset() {
	*x = RedisBenchmarkSpec{}
	mi := &file_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisBenchmarkSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisBenchmarkSpec) ProtoMessage() {}

func (x *RedisBenchmarkSpec) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisBenchmarkSpec.ProtoReflect.Descriptor instead.
func (*RedisBenchmarkSpec) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0}
}

func (x *RedisBenchmarkSpec) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RedisBenchmarkSpec) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RedisBenchmarkSpec) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *RedisBenchmarkSpec) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RedisBenchmarkSpec) GetRequests() string {
	if x != nil {
		return x.Requests
	}
	return ""
}

func (x *RedisBenchmarkSpec) GetClients() string {
	if x != nil {
		return x.Clients
	}
	return ""
}

func (x *RedisBenchmarkSpec) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *RedisBenchmarkSpec) GetLoop() string {
	if x != nil {
		return x.Loop
	}
	return ""
}

func (x *RedisBenchmarkSpec) GetLoopDuration() string {
	if x != nil {
		return x.LoopDuration
	}
	return ""
}

// 请求消息：创建任务
type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 任务名称
	Spec          *RedisBenchmarkSpec    `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"` // Redis 基准测试的参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetSpec() *RedisBenchmarkSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// 响应消息：创建任务
type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 请求消息：启动任务
type StartTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTaskRequest) Reset() {
	*x = StartTaskRequest{}
	mi := &file_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTaskRequest) ProtoMessage() {}

func (x *StartTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTaskRequest.ProtoReflect.Descriptor instead.
func (*StartTaskRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{3}
}

func (x *StartTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 响应消息：启动任务
type StartTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTaskResponse) Reset() {
	*x = StartTaskResponse{}
	mi := &file_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTaskResponse) ProtoMessage() {}

func (x *StartTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTaskResponse.ProtoReflect.Descriptor instead.
func (*StartTaskResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{4}
}

func (x *StartTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 请求消息：停止任务
type StopTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTaskRequest) Reset() {
	*x = StopTaskRequest{}
	mi := &file_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskRequest) ProtoMessage() {}

func (x *StopTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskRequest.ProtoReflect.Descriptor instead.
func (*StopTaskRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{5}
}

func (x *StopTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 响应消息：停止任务
type StopTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTaskResponse) Reset() {
	*x = StopTaskResponse{}
	mi := &file_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskResponse) ProtoMessage() {}

func (x *StopTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskResponse.ProtoReflect.Descriptor instead.
func (*StopTaskResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{6}
}

func (x *StopTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 请求消息：获取任务状态
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{7}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 响应消息：获取任务状态
type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"` // 输出
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{8}
}

func (x *GetTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTaskResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

// 请求消息：获取任务输出
type GetTaskOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskOutputRequest) Reset() {
	*x = GetTaskOutputRequest{}
	mi := &file_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskOutputRequest) ProtoMessage() {}

func (x *GetTaskOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskOutputRequest.ProtoReflect.Descriptor instead.
func (*GetTaskOutputRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{9}
}

func (x *GetTaskOutputRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 响应消息：获取任务输出
type GetTaskOutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []string               `protobuf:"bytes,1,rep,name=output,proto3" json:"output,omitempty"` // 输出
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskOutputResponse) Reset() {
	*x = GetTaskOutputResponse{}
	mi := &file_command_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskOutputResponse) ProtoMessage() {}

func (x *GetTaskOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskOutputResponse.ProtoReflect.Descriptor instead.
func (*GetTaskOutputResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{10}
}

func (x *GetTaskOutputResponse) GetOutput() []string {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_command_proto protoreflect.FileDescriptor

const file_command_proto_rawDesc = "" +
	"\n" +
	"\rcommand.proto\x12\acommand\"\xfb\x01\n" +
	"\x12RedisBenchmarkSpec\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1a\n" +
	"\brequests\x18\x05 \x01(\tR\brequests\x12\x18\n" +
	"\aclients\x18\x06 \x01(\tR\aclients\x12\x12\n" +
	"\x04size\x18\a \x01(\tR\x04size\x12\x12\n" +
	"\x04loop\x18\b \x01(\tR\x04loop\x12#\n" +
	"\rloop_duration\x18\t \x01(\tR\floopDuration\"X\n" +
	"\x11CreateTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x04spec\x18\x02 \x01(\v2\x1b.command.RedisBenchmarkSpecR\x04spec\"-\n" +
	"\x12CreateTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"+\n" +
	"\x10StartTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"+\n" +
	"\x11StartTaskResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"*\n" +
	"\x0fStopTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"*\n" +
	"\x10StopTaskResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"A\n" +
	"\x0fGetTaskResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\"/\n" +
	"\x14GetTaskOutputRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"/\n" +
	"\x15GetTaskOutputResponse\x12\x16\n" +
	"\x06output\x18\x01 \x03(\tR\x06output2\xeb\x02\n" +
	"\x0fCommandExecutor\x12E\n" +
	"\n" +
	"CreateTask\x12\x1a.command.CreateTaskRequest\x1a\x1b.command.CreateTaskResponse\x12B\n" +
	"\tStartTask\x12\x19.command.StartTaskRequest\x1a\x1a.command.StartTaskResponse\x12?\n" +
	"\bStopTask\x12\x18.command.StopTaskRequest\x1a\x19.command.StopTaskResponse\x12<\n" +
	"\aGetTask\x12\x17.command.GetTaskRequest\x1a\x18.command.GetTaskResponse\x12N\n" +
	"\rGetTaskOutput\x12\x1d.command.GetTaskOutputRequest\x1a\x1e.command.GetTaskOutputResponseB\x1cZ\x1agithub.com/chaos-mesh/grpcb\x06proto3"

var (
	file_command_proto_rawDescOnce sync.Once
	file_command_proto_rawDescData []byte
)

func file_command_proto_rawDescGZIP() []byte {
	file_command_proto_rawDescOnce.Do(func() {
		file_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)))
	})
	return file_command_proto_rawDescData
}

var file_command_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_command_proto_goTypes = []any{
	(*RedisBenchmarkSpec)(nil),    // 0: command.RedisBenchmarkSpec
	(*CreateTaskRequest)(nil),     // 1: command.CreateTaskRequest
	(*CreateTaskResponse)(nil),    // 2: command.CreateTaskResponse
	(*StartTaskRequest)(nil),      // 3: command.StartTaskRequest
	(*StartTaskResponse)(nil),     // 4: command.StartTaskResponse
	(*StopTaskRequest)(nil),       // 5: command.StopTaskRequest
	(*StopTaskResponse)(nil),      // 6: command.StopTaskResponse
	(*GetTaskRequest)(nil),        // 7: command.GetTaskRequest
	(*GetTaskResponse)(nil),       // 8: command.GetTaskResponse
	(*GetTaskOutputRequest)(nil),  // 9: command.GetTaskOutputRequest
	(*GetTaskOutputResponse)(nil), // 10: command.GetTaskOutputResponse
}
var file_command_proto_depIdxs = []int32{
	0,  // 0: command.CreateTaskRequest.spec:type_name -> command.RedisBenchmarkSpec
	1,  // 1: command.CommandExecutor.CreateTask:input_type -> command.CreateTaskRequest
	3,  // 2: command.CommandExecutor.StartTask:input_type -> command.StartTaskRequest
	5,  // 3: command.CommandExecutor.StopTask:input_type -> command.StopTaskRequest
	7,  // 4: command.CommandExecutor.GetTask:input_type -> command.GetTaskRequest
	9,  // 5: command.CommandExecutor.GetTaskOutput:input_type -> command.GetTaskOutputRequest
	2,  // 6: command.CommandExecutor.CreateTask:output_type -> command.CreateTaskResponse
	4,  // 7: command.CommandExecutor.StartTask:output_type -> command.StartTaskResponse
	6,  // 8: command.CommandExecutor.StopTask:output_type -> command.StopTaskResponse
	8,  // 9: command.CommandExecutor.GetTask:output_type -> command.GetTaskResponse
	10, // 10: command.CommandExecutor.GetTaskOutput:output_type -> command.GetTaskOutputResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_command_proto_init() }
func file_command_proto_init() {
	if File_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_command_proto_goTypes,
		DependencyIndexes: file_command_proto_depIdxs,
		MessageInfos:      file_command_proto_msgTypes,
	}.Build()
	File_command_proto = out.File
	file_command_proto_goTypes = nil
	file_command_proto_depIdxs = nil
}
