// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package _0250818

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommandExecutorClient is the client API for CommandExecutor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandExecutorClient interface {
	// 创建任务
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
	// 启动任务
	StartTask(ctx context.Context, in *StartTaskRequest, opts ...grpc.CallOption) (*StartTaskResponse, error)
	// 停止任务
	StopTask(ctx context.Context, in *StopTaskRequest, opts ...grpc.CallOption) (*StopTaskResponse, error)
	// 获取任务状态
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
	// 获取任务输出
	GetTaskOutput(ctx context.Context, in *GetTaskOutputRequest, opts ...grpc.CallOption) (*GetTaskOutputResponse, error)
	// 新增 Kafka 生产者性能测试方法
	StartKafkaProducerTest(ctx context.Context, in *KafkaProducerSpec, opts ...grpc.CallOption) (CommandExecutor_StartKafkaProducerTestClient, error)
	// 新增 Kafka 消费者性能测试方法
	StartKafkaConsumerTest(ctx context.Context, in *KafkaConsumerSpec, opts ...grpc.CallOption) (CommandExecutor_StartKafkaConsumerTestClient, error)
}

type commandExecutorClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandExecutorClient(cc grpc.ClientConnInterface) CommandExecutorClient {
	return &commandExecutorClient{cc}
}

func (c *commandExecutorClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	out := new(CreateTaskResponse)
	err := c.cc.Invoke(ctx, "/CommandExecutor/CreateTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandExecutorClient) StartTask(ctx context.Context, in *StartTaskRequest, opts ...grpc.CallOption) (*StartTaskResponse, error) {
	out := new(StartTaskResponse)
	err := c.cc.Invoke(ctx, "/CommandExecutor/StartTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandExecutorClient) StopTask(ctx context.Context, in *StopTaskRequest, opts ...grpc.CallOption) (*StopTaskResponse, error) {
	out := new(StopTaskResponse)
	err := c.cc.Invoke(ctx, "/CommandExecutor/StopTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandExecutorClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, "/CommandExecutor/GetTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandExecutorClient) GetTaskOutput(ctx context.Context, in *GetTaskOutputRequest, opts ...grpc.CallOption) (*GetTaskOutputResponse, error) {
	out := new(GetTaskOutputResponse)
	err := c.cc.Invoke(ctx, "/CommandExecutor/GetTaskOutput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandExecutorClient) StartKafkaProducerTest(ctx context.Context, in *KafkaProducerSpec, opts ...grpc.CallOption) (CommandExecutor_StartKafkaProducerTestClient, error) {
	stream, err := c.cc.NewStream(ctx, &CommandExecutor_ServiceDesc.Streams[0], "/CommandExecutor/StartKafkaProducerTest", opts...)
	if err != nil {
		return nil, err
	}
	x := &commandExecutorStartKafkaProducerTestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CommandExecutor_StartKafkaProducerTestClient interface {
	Recv() (*CommandResponse, error)
	grpc.ClientStream
}

type commandExecutorStartKafkaProducerTestClient struct {
	grpc.ClientStream
}

func (x *commandExecutorStartKafkaProducerTestClient) Recv() (*CommandResponse, error) {
	m := new(CommandResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *commandExecutorClient) StartKafkaConsumerTest(ctx context.Context, in *KafkaConsumerSpec, opts ...grpc.CallOption) (CommandExecutor_StartKafkaConsumerTestClient, error) {
	stream, err := c.cc.NewStream(ctx, &CommandExecutor_ServiceDesc.Streams[1], "/CommandExecutor/StartKafkaConsumerTest", opts...)
	if err != nil {
		return nil, err
	}
	x := &commandExecutorStartKafkaConsumerTestClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CommandExecutor_StartKafkaConsumerTestClient interface {
	Recv() (*CommandResponse, error)
	grpc.ClientStream
}

type commandExecutorStartKafkaConsumerTestClient struct {
	grpc.ClientStream
}

func (x *commandExecutorStartKafkaConsumerTestClient) Recv() (*CommandResponse, error) {
	m := new(CommandResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CommandExecutorServer is the server API for CommandExecutor service.
// All implementations must embed UnimplementedCommandExecutorServer
// for forward compatibility
type CommandExecutorServer interface {
	// 创建任务
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	// 启动任务
	StartTask(context.Context, *StartTaskRequest) (*StartTaskResponse, error)
	// 停止任务
	StopTask(context.Context, *StopTaskRequest) (*StopTaskResponse, error)
	// 获取任务状态
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	// 获取任务输出
	GetTaskOutput(context.Context, *GetTaskOutputRequest) (*GetTaskOutputResponse, error)
	// 新增 Kafka 生产者性能测试方法
	StartKafkaProducerTest(*KafkaProducerSpec, CommandExecutor_StartKafkaProducerTestServer) error
	// 新增 Kafka 消费者性能测试方法
	StartKafkaConsumerTest(*KafkaConsumerSpec, CommandExecutor_StartKafkaConsumerTestServer) error
	mustEmbedUnimplementedCommandExecutorServer()
}

// UnimplementedCommandExecutorServer must be embedded to have forward compatible implementations.
type UnimplementedCommandExecutorServer struct {
}

func (UnimplementedCommandExecutorServer) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedCommandExecutorServer) StartTask(context.Context, *StartTaskRequest) (*StartTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTask not implemented")
}
func (UnimplementedCommandExecutorServer) StopTask(context.Context, *StopTaskRequest) (*StopTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopTask not implemented")
}
func (UnimplementedCommandExecutorServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedCommandExecutorServer) GetTaskOutput(context.Context, *GetTaskOutputRequest) (*GetTaskOutputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskOutput not implemented")
}
func (UnimplementedCommandExecutorServer) StartKafkaProducerTest(*KafkaProducerSpec, CommandExecutor_StartKafkaProducerTestServer) error {
	return status.Errorf(codes.Unimplemented, "method StartKafkaProducerTest not implemented")
}
func (UnimplementedCommandExecutorServer) StartKafkaConsumerTest(*KafkaConsumerSpec, CommandExecutor_StartKafkaConsumerTestServer) error {
	return status.Errorf(codes.Unimplemented, "method StartKafkaConsumerTest not implemented")
}
func (UnimplementedCommandExecutorServer) mustEmbedUnimplementedCommandExecutorServer() {}

// UnsafeCommandExecutorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandExecutorServer will
// result in compilation errors.
type UnsafeCommandExecutorServer interface {
	mustEmbedUnimplementedCommandExecutorServer()
}

func RegisterCommandExecutorServer(s grpc.ServiceRegistrar, srv CommandExecutorServer) {
	s.RegisterService(&CommandExecutor_ServiceDesc, srv)
}

func _CommandExecutor_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandExecutorServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CommandExecutor/CreateTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandExecutorServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandExecutor_StartTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandExecutorServer).StartTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CommandExecutor/StartTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandExecutorServer).StartTask(ctx, req.(*StartTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandExecutor_StopTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandExecutorServer).StopTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CommandExecutor/StopTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandExecutorServer).StopTask(ctx, req.(*StopTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandExecutor_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandExecutorServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CommandExecutor/GetTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandExecutorServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandExecutor_GetTaskOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandExecutorServer).GetTaskOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CommandExecutor/GetTaskOutput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandExecutorServer).GetTaskOutput(ctx, req.(*GetTaskOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandExecutor_StartKafkaProducerTest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(KafkaProducerSpec)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommandExecutorServer).StartKafkaProducerTest(m, &commandExecutorStartKafkaProducerTestServer{stream})
}

type CommandExecutor_StartKafkaProducerTestServer interface {
	Send(*CommandResponse) error
	grpc.ServerStream
}

type commandExecutorStartKafkaProducerTestServer struct {
	grpc.ServerStream
}

func (x *commandExecutorStartKafkaProducerTestServer) Send(m *CommandResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CommandExecutor_StartKafkaConsumerTest_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(KafkaConsumerSpec)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommandExecutorServer).StartKafkaConsumerTest(m, &commandExecutorStartKafkaConsumerTestServer{stream})
}

type CommandExecutor_StartKafkaConsumerTestServer interface {
	Send(*CommandResponse) error
	grpc.ServerStream
}

type commandExecutorStartKafkaConsumerTestServer struct {
	grpc.ServerStream
}

func (x *commandExecutorStartKafkaConsumerTestServer) Send(m *CommandResponse) error {
	return x.ServerStream.SendMsg(m)
}

// CommandExecutor_ServiceDesc is the grpc.ServiceDesc for CommandExecutor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandExecutor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CommandExecutor",
	HandlerType: (*CommandExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _CommandExecutor_CreateTask_Handler,
		},
		{
			MethodName: "StartTask",
			Handler:    _CommandExecutor_StartTask_Handler,
		},
		{
			MethodName: "StopTask",
			Handler:    _CommandExecutor_StopTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _CommandExecutor_GetTask_Handler,
		},
		{
			MethodName: "GetTaskOutput",
			Handler:    _CommandExecutor_GetTaskOutput_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartKafkaProducerTest",
			Handler:       _CommandExecutor_StartKafkaProducerTest_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StartKafkaConsumerTest",
			Handler:       _CommandExecutor_StartKafkaConsumerTest_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "command.proto",
}
