// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.15.2
// source: command.proto

package _0250818

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RedisBenchmarkSpec 定义 Redis 基准测试的参数
type RedisBenchmarkSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`                                 // 操作类型
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`                             // Redis 服务器地址
	Port          string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`                                     // Redis 服务器端口
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`                             // Redis 密码（可选）
	Requests      string                 `protobuf:"bytes,5,opt,name=requests,proto3" json:"requests,omitempty"`                             // 请求总数
	Clients       string                 `protobuf:"bytes,6,opt,name=clients,proto3" json:"clients,omitempty"`                               // 并发客户端数
	Size          string                 `protobuf:"bytes,7,opt,name=size,proto3" json:"size,omitempty"`                                     // 请求大小（可选）
	Loop          string                 `protobuf:"bytes,8,opt,name=loop,proto3" json:"loop,omitempty"`                                     // 循环次数（可选）
	LoopDuration  string                 `protobuf:"bytes,9,opt,name=loop_duration,json=loopDuration,proto3" json:"loop_duration,omitempty"` // 循环持续时间（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisBenchmarkSpec) Reset() {
	*x = RedisBenchmarkSpec{}
	mi := &file_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisBenchmarkSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisBenchmarkSpec) ProtoMessage() {}

func (x *RedisBenchmarkSpec) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisBenchmarkSpec.ProtoReflect.Descriptor instead.
func (*RedisBenchmarkSpec) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0}
}

func (x *RedisBenchmarkSpec) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *RedisBenchmarkSpec) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RedisBenchmarkSpec) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *RedisBenchmarkSpec) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RedisBenchmarkSpec) GetRequests() string {
	if x != nil {
		return x.Requests
	}
	return ""
}

func (x *RedisBenchmarkSpec) GetClients() string {
	if x != nil {
		return x.Clients
	}
	return ""
}

func (x *RedisBenchmarkSpec) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *RedisBenchmarkSpec) GetLoop() string {
	if x != nil {
		return x.Loop
	}
	return ""
}

func (x *RedisBenchmarkSpec) GetLoopDuration() string {
	if x != nil {
		return x.LoopDuration
	}
	return ""
}

// Kafka 生产者性能测试的参数
type KafkaProducerSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Topic            string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`                                               // Kafka 主题
	NumRecords       string                 `protobuf:"bytes,2,opt,name=num_records,json=numRecords,proto3" json:"num_records,omitempty"`                   // 发送消息数量
	RecordSize       string                 `protobuf:"bytes,3,opt,name=record_size,json=recordSize,proto3" json:"record_size,omitempty"`                   // 消息大小
	Acks             string                 `protobuf:"bytes,4,opt,name=acks,proto3" json:"acks,omitempty"`                                                 // 确认级别
	CompressionType  string                 `protobuf:"bytes,5,opt,name=compression_type,json=compressionType,proto3" json:"compression_type,omitempty"`    // 压缩类型
	BootstrapServers string                 `protobuf:"bytes,6,opt,name=bootstrap_servers,json=bootstrapServers,proto3" json:"bootstrap_servers,omitempty"` // 服务器地址
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KafkaProducerSpec) Reset() {
	*x = KafkaProducerSpec{}
	mi := &file_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KafkaProducerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaProducerSpec) ProtoMessage() {}

func (x *KafkaProducerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaProducerSpec.ProtoReflect.Descriptor instead.
func (*KafkaProducerSpec) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{1}
}

func (x *KafkaProducerSpec) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *KafkaProducerSpec) GetNumRecords() string {
	if x != nil {
		return x.NumRecords
	}
	return ""
}

func (x *KafkaProducerSpec) GetRecordSize() string {
	if x != nil {
		return x.RecordSize
	}
	return ""
}

func (x *KafkaProducerSpec) GetAcks() string {
	if x != nil {
		return x.Acks
	}
	return ""
}

func (x *KafkaProducerSpec) GetCompressionType() string {
	if x != nil {
		return x.CompressionType
	}
	return ""
}

func (x *KafkaProducerSpec) GetBootstrapServers() string {
	if x != nil {
		return x.BootstrapServers
	}
	return ""
}

// Kafka 消费者性能测试的参数
type KafkaConsumerSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Topic            string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`                                               // Kafka 主题
	BootstrapServers string                 `protobuf:"bytes,2,opt,name=bootstrap_servers,json=bootstrapServers,proto3" json:"bootstrap_servers,omitempty"` // 服务器地址
	Messages         string                 `protobuf:"bytes,3,opt,name=messages,proto3" json:"messages,omitempty"`                                         // 消息数量
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KafkaConsumerSpec) Reset() {
	*x = KafkaConsumerSpec{}
	mi := &file_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KafkaConsumerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KafkaConsumerSpec) ProtoMessage() {}

func (x *KafkaConsumerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KafkaConsumerSpec.ProtoReflect.Descriptor instead.
func (*KafkaConsumerSpec) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{2}
}

func (x *KafkaConsumerSpec) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *KafkaConsumerSpec) GetBootstrapServers() string {
	if x != nil {
		return x.BootstrapServers
	}
	return ""
}

func (x *KafkaConsumerSpec) GetMessages() string {
	if x != nil {
		return x.Messages
	}
	return ""
}

// 请求消息：创建任务
type CreateTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 任务名称
	// Types that are valid to be assigned to TaskSpec:
	//
	//	*CreateTaskRequest_RedisSpec
	//	*CreateTaskRequest_KafkaProducerSpec
	//	*CreateTaskRequest_KafkaConsumerSpec
	TaskSpec      isCreateTaskRequest_TaskSpec `protobuf_oneof:"task_spec"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetTaskSpec() isCreateTaskRequest_TaskSpec {
	if x != nil {
		return x.TaskSpec
	}
	return nil
}

func (x *CreateTaskRequest) GetRedisSpec() *RedisBenchmarkSpec {
	if x != nil {
		if x, ok := x.TaskSpec.(*CreateTaskRequest_RedisSpec); ok {
			return x.RedisSpec
		}
	}
	return nil
}

func (x *CreateTaskRequest) GetKafkaProducerSpec() *KafkaProducerSpec {
	if x != nil {
		if x, ok := x.TaskSpec.(*CreateTaskRequest_KafkaProducerSpec); ok {
			return x.KafkaProducerSpec
		}
	}
	return nil
}

func (x *CreateTaskRequest) GetKafkaConsumerSpec() *KafkaConsumerSpec {
	if x != nil {
		if x, ok := x.TaskSpec.(*CreateTaskRequest_KafkaConsumerSpec); ok {
			return x.KafkaConsumerSpec
		}
	}
	return nil
}

type isCreateTaskRequest_TaskSpec interface {
	isCreateTaskRequest_TaskSpec()
}

type CreateTaskRequest_RedisSpec struct {
	RedisSpec *RedisBenchmarkSpec `protobuf:"bytes,2,opt,name=redis_spec,json=redisSpec,proto3,oneof"` // Redis 基准测试的参数
}

type CreateTaskRequest_KafkaProducerSpec struct {
	KafkaProducerSpec *KafkaProducerSpec `protobuf:"bytes,3,opt,name=kafka_producer_spec,json=kafkaProducerSpec,proto3,oneof"` // Kafka 生产者性能测试的参数
}

type CreateTaskRequest_KafkaConsumerSpec struct {
	KafkaConsumerSpec *KafkaConsumerSpec `protobuf:"bytes,4,opt,name=kafka_consumer_spec,json=kafkaConsumerSpec,proto3,oneof"` // Kafka 消费者性能测试的参数
}

func (*CreateTaskRequest_RedisSpec) isCreateTaskRequest_TaskSpec() {}

func (*CreateTaskRequest_KafkaProducerSpec) isCreateTaskRequest_TaskSpec() {}

func (*CreateTaskRequest_KafkaConsumerSpec) isCreateTaskRequest_TaskSpec() {}

// 响应消息：创建任务
type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 请求消息：启动任务
type StartTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTaskRequest) Reset() {
	*x = StartTaskRequest{}
	mi := &file_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTaskRequest) ProtoMessage() {}

func (x *StartTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTaskRequest.ProtoReflect.Descriptor instead.
func (*StartTaskRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{5}
}

func (x *StartTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 响应消息：启动任务
type StartTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTaskResponse) Reset() {
	*x = StartTaskResponse{}
	mi := &file_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTaskResponse) ProtoMessage() {}

func (x *StartTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTaskResponse.ProtoReflect.Descriptor instead.
func (*StartTaskResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{6}
}

func (x *StartTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 请求消息：停止任务
type StopTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTaskRequest) Reset() {
	*x = StopTaskRequest{}
	mi := &file_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskRequest) ProtoMessage() {}

func (x *StopTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskRequest.ProtoReflect.Descriptor instead.
func (*StopTaskRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{7}
}

func (x *StopTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 响应消息：停止任务
type StopTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTaskResponse) Reset() {
	*x = StopTaskResponse{}
	mi := &file_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskResponse) ProtoMessage() {}

func (x *StopTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskResponse.ProtoReflect.Descriptor instead.
func (*StopTaskResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{8}
}

func (x *StopTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 请求消息：获取任务状态
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{9}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 响应消息：获取任务状态
type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"` // 输出
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_command_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{10}
}

func (x *GetTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTaskResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

// 请求消息：获取任务输出
type GetTaskOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"` // 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskOutputRequest) Reset() {
	*x = GetTaskOutputRequest{}
	mi := &file_command_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskOutputRequest) ProtoMessage() {}

func (x *GetTaskOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskOutputRequest.ProtoReflect.Descriptor instead.
func (*GetTaskOutputRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{11}
}

func (x *GetTaskOutputRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// 响应消息：获取任务输出
type GetTaskOutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []string               `protobuf:"bytes,1,rep,name=output,proto3" json:"output,omitempty"` // 输出
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskOutputResponse) Reset() {
	*x = GetTaskOutputResponse{}
	mi := &file_command_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskOutputResponse) ProtoMessage() {}

func (x *GetTaskOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskOutputResponse.ProtoReflect.Descriptor instead.
func (*GetTaskOutputResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{12}
}

func (x *GetTaskOutputResponse) GetOutput() []string {
	if x != nil {
		return x.Output
	}
	return nil
}

// 命令执行响应
type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"` // 输出
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_command_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{13}
}

func (x *CommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_command_proto protoreflect.FileDescriptor

const file_command_proto_rawDesc = "" +
	"\n" +
	"\rcommand.proto\"\xfb\x01\n" +
	"\x12RedisBenchmarkSpec\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1a\n" +
	"\brequests\x18\x05 \x01(\tR\brequests\x12\x18\n" +
	"\aclients\x18\x06 \x01(\tR\aclients\x12\x12\n" +
	"\x04size\x18\a \x01(\tR\x04size\x12\x12\n" +
	"\x04loop\x18\b \x01(\tR\x04loop\x12#\n" +
	"\rloop_duration\x18\t \x01(\tR\floopDuration\"\xd7\x01\n" +
	"\x11KafkaProducerSpec\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1f\n" +
	"\vnum_records\x18\x02 \x01(\tR\n" +
	"numRecords\x12\x1f\n" +
	"\vrecord_size\x18\x03 \x01(\tR\n" +
	"recordSize\x12\x12\n" +
	"\x04acks\x18\x04 \x01(\tR\x04acks\x12)\n" +
	"\x10compression_type\x18\x05 \x01(\tR\x0fcompressionType\x12+\n" +
	"\x11bootstrap_servers\x18\x06 \x01(\tR\x10bootstrapServers\"r\n" +
	"\x11KafkaConsumerSpec\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12+\n" +
	"\x11bootstrap_servers\x18\x02 \x01(\tR\x10bootstrapServers\x12\x1a\n" +
	"\bmessages\x18\x03 \x01(\tR\bmessages\"\xf6\x01\n" +
	"\x11CreateTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\n" +
	"redis_spec\x18\x02 \x01(\v2\x13.RedisBenchmarkSpecH\x00R\tredisSpec\x12D\n" +
	"\x13kafka_producer_spec\x18\x03 \x01(\v2\x12.KafkaProducerSpecH\x00R\x11kafkaProducerSpec\x12D\n" +
	"\x13kafka_consumer_spec\x18\x04 \x01(\v2\x12.KafkaConsumerSpecH\x00R\x11kafkaConsumerSpecB\v\n" +
	"\ttask_spec\"-\n" +
	"\x12CreateTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"+\n" +
	"\x10StartTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"+\n" +
	"\x11StartTaskResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"*\n" +
	"\x0fStopTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"*\n" +
	"\x10StopTaskResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"A\n" +
	"\x0fGetTaskResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\"/\n" +
	"\x14GetTaskOutputRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"/\n" +
	"\x15GetTaskOutputResponse\x12\x16\n" +
	"\x06output\x18\x01 \x03(\tR\x06output\")\n" +
	"\x0fCommandResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output2\x9f\x03\n" +
	"\x0fCommandExecutor\x125\n" +
	"\n" +
	"CreateTask\x12\x12.CreateTaskRequest\x1a\x13.CreateTaskResponse\x122\n" +
	"\tStartTask\x12\x11.StartTaskRequest\x1a\x12.StartTaskResponse\x12/\n" +
	"\bStopTask\x12\x10.StopTaskRequest\x1a\x11.StopTaskResponse\x12,\n" +
	"\aGetTask\x12\x0f.GetTaskRequest\x1a\x10.GetTaskResponse\x12>\n" +
	"\rGetTaskOutput\x12\x15.GetTaskOutputRequest\x1a\x16.GetTaskOutputResponse\x12@\n" +
	"\x16StartKafkaProducerTest\x12\x12.KafkaProducerSpec\x1a\x10.CommandResponse0\x01\x12@\n" +
	"\x16StartKafkaConsumerTest\x12\x12.KafkaConsumerSpec\x1a\x10.CommandResponse0\x01B#Z!github.com/QuchengRep1/chaos-grpcb\x06proto3"

var (
	file_command_proto_rawDescOnce sync.Once
	file_command_proto_rawDescData []byte
)

func file_command_proto_rawDescGZIP() []byte {
	file_command_proto_rawDescOnce.Do(func() {
		file_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)))
	})
	return file_command_proto_rawDescData
}

var file_command_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_command_proto_goTypes = []any{
	(*RedisBenchmarkSpec)(nil),    // 0: RedisBenchmarkSpec
	(*KafkaProducerSpec)(nil),     // 1: KafkaProducerSpec
	(*KafkaConsumerSpec)(nil),     // 2: KafkaConsumerSpec
	(*CreateTaskRequest)(nil),     // 3: CreateTaskRequest
	(*CreateTaskResponse)(nil),    // 4: CreateTaskResponse
	(*StartTaskRequest)(nil),      // 5: StartTaskRequest
	(*StartTaskResponse)(nil),     // 6: StartTaskResponse
	(*StopTaskRequest)(nil),       // 7: StopTaskRequest
	(*StopTaskResponse)(nil),      // 8: StopTaskResponse
	(*GetTaskRequest)(nil),        // 9: GetTaskRequest
	(*GetTaskResponse)(nil),       // 10: GetTaskResponse
	(*GetTaskOutputRequest)(nil),  // 11: GetTaskOutputRequest
	(*GetTaskOutputResponse)(nil), // 12: GetTaskOutputResponse
	(*CommandResponse)(nil),       // 13: CommandResponse
}
var file_command_proto_depIdxs = []int32{
	0,  // 0: CreateTaskRequest.redis_spec:type_name -> RedisBenchmarkSpec
	1,  // 1: CreateTaskRequest.kafka_producer_spec:type_name -> KafkaProducerSpec
	2,  // 2: CreateTaskRequest.kafka_consumer_spec:type_name -> KafkaConsumerSpec
	3,  // 3: CommandExecutor.CreateTask:input_type -> CreateTaskRequest
	5,  // 4: CommandExecutor.StartTask:input_type -> StartTaskRequest
	7,  // 5: CommandExecutor.StopTask:input_type -> StopTaskRequest
	9,  // 6: CommandExecutor.GetTask:input_type -> GetTaskRequest
	11, // 7: CommandExecutor.GetTaskOutput:input_type -> GetTaskOutputRequest
	1,  // 8: CommandExecutor.StartKafkaProducerTest:input_type -> KafkaProducerSpec
	2,  // 9: CommandExecutor.StartKafkaConsumerTest:input_type -> KafkaConsumerSpec
	4,  // 10: CommandExecutor.CreateTask:output_type -> CreateTaskResponse
	6,  // 11: CommandExecutor.StartTask:output_type -> StartTaskResponse
	8,  // 12: CommandExecutor.StopTask:output_type -> StopTaskResponse
	10, // 13: CommandExecutor.GetTask:output_type -> GetTaskResponse
	12, // 14: CommandExecutor.GetTaskOutput:output_type -> GetTaskOutputResponse
	13, // 15: CommandExecutor.StartKafkaProducerTest:output_type -> CommandResponse
	13, // 16: CommandExecutor.StartKafkaConsumerTest:output_type -> CommandResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_command_proto_init() }
func file_command_proto_init() {
	if File_command_proto != nil {
		return
	}
	file_command_proto_msgTypes[3].OneofWrappers = []any{
		(*CreateTaskRequest_RedisSpec)(nil),
		(*CreateTaskRequest_KafkaProducerSpec)(nil),
		(*CreateTaskRequest_KafkaConsumerSpec)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_command_proto_goTypes,
		DependencyIndexes: file_command_proto_depIdxs,
		MessageInfos:      file_command_proto_msgTypes,
	}.Build()
	File_command_proto = out.File
	file_command_proto_goTypes = nil
	file_command_proto_depIdxs = nil
}
